### ISSUE TITLE
Can't load sheetfu

### ISSUE THREAD

**Issue by kkwan-tc** [socialpoint-labs/sheetfu#12]
Hi, 
Just installed this today, and I'm unable to import sheetfu.

![image](https://user-images.githubusercontent.com/40668524/54444210-a2586500-4718-11e9-92d7-8c93262d99f3.png)

Wondering if I missed something.
I'm running this in a virtual environment with Python 3.6.5

Thanks!

**Comment by kkwan-tc** [comment]
Update, as I'm not well versed. When installing the package the modules directory is not being included. I've resolved it by manually copying the modules directory into sheetfu installed directory.

**Comment by sp-philippe-oger** [comment]
Hey Kkwan.
Sorry for not getting back yo your earlier. This has been fixed this morning. A simple PIP install should will now include the Table module.

**Comment by kkwanyang** [comment]
Thanks for fixing it!
