### ISSUE TITLE
Sorting datetime values

### ISSUE THREAD

**Issue by SP-alex-muelas** [socialpoint-labs/sheetfu#23]
Datetime fields are converted with the datetime_to_serial_number function to integers on writing to the sheet. However, this can be a problem right now when sorting, as python will attempt to compare a datetime object (from a newly added item) with an int object (read from the existing table) and break.

Perhaps datetime objects should be converted to ints when adding them to the table, or they should be read as dates when loading the table (either one of those options would work).

Example of a code that breaks:
table = Table(data_range)
table.add_one({"Date": datetime.now()})
table.commit()

Later...
table = Table(data_range)
table.add_one({"Date": datetime.now()})
table.sort("Date")

the comparison of the previously added Date (an int now) with the newly added Date (datetime) will throw a TypeError

**Comment by sp-philippe-oger** [comment]
This is indeed a problem. Been thinking of it already, and was thinking of the following solution. I'd love your thoughts on this.

One way to adjust would be by forcing cast to a field when we instantiate the table. Something like this.

```python
casts = {'Date':datetime}
table = Table(data_range, typecasting=casts)
table.add_one({"Date": datetime.now()})
table.commit()
```

Under the hood, when instantiating the table object, it would parse this field to make sure the value is a datetime object when you use the table. It would also know how to parse it perfectly when you commit the table.

I'm thinking of 3 types that could really benefits from it: datetime, object, and also array (which could work like object probably). If you have a column that contains json string, it would be nice to have them as a python dictionary natively when we instantiate the Table. We would not need to worry about json.dump() or json.load() anymore. Same applies for the array.

In practice, this could look like this

```python
from datetime import datetime

casts = {"Date": datetime, "json column": dict, "my array column": list}
table = Table(data_range, typecasting=casts)

item = {
    "Date": datetime.now(), 
    "json column": {"name": "john", "surname":"doe"}, 
    "my array column": [1, 2, 3]
}

table.add_one(item)
table.commit()
```

What do you think?

**Comment by philippe2803** [comment]
For string, number and boolean, this is already handled here https://github.com/socialpoint-labs/sheetfu/blob/master/sheetfu/parsers.py#L10

**Comment by philippe2803** [comment]
@sp-adrian-matteo @SP-alex-muelas @sp-daniel-sanchez 

Would you be interested into adding this feature or should I close this issue?

**Comment by SP-alex-muelas** [comment]
I would leave the issue open, I think this is still relevant.

I was skeptical at first about the casting solution, as plenty of times you want to instantiate a column without knowing its type, but the more I think about it the more I like it.

We'd just need to make sure the casts apply on any kind of operation where an item is added (read, add_one for now).

Another question is: how do we exactly cast the value to the desired type? Would we need to treat each case of input-output sepparately?

**Comment by philippe2803** [comment]
Glad to hear. I think that would be a kick ass feature.
I imagine the casting magic should happen at Item level, but I'll let you decide on this.

To answer your last question, I'm not quite sure what is the best implementation. Let's do a quick overview of the types.
 - String, numbers and boolean are already handled properly.
 - Type of interest is Datetime and Json. For those 2 types, we could have built-in parsers that handles the cast properly in get and set values.
 - We could also let the user to set their own parsers by passing some executables as parameters.

Demo time. 
For builtin, it would be just like the one I posted above

```python

casts = {"Date": "datetime", "json column": "json"} .  # using builtin parsers
table = Table(data_range, typecasting=casts)

item = {
    "Date": datetime.now(),
    "json column": {"name": "john", "surname":"doe"},
}

table.add_one(item)
table.commit()

```
That would work for most cases.


Now, let's say we have a sheet that has a date column, but the values are in iso format in the sheet and must be kept this way. When instantiating, the Date column values will be seen as string, so we could use custom casts functions for both get and set to make sure the Table object see them as Datetime object, without changing the isoformat string from the sheet.
 

```python
from datetime import datetime


def get_date_from_iso(date_string):
    return datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S.%fZ")

def set_date_to_iso(datetime_object):
    return datetime_object.isoformat()

casts = {
    "Date": {"getter":  get_date_from_iso, "setter": set_date_to_iso}, 
    "json column": "json"
}

table = Table(data_range, typecasting=casts)

item = {
    "Date": datetime.now(),
    "json column": {"name": "john", "surname":"doe"},
}

table.add_one(item)
table.commit()

```
The executables could be passed to the CellParsers class in some way, and apply the parsing there. That would work pretty well. Maybe it is overkill though? 

Thoughts?

**Comment by SP-alex-muelas** [comment]
I like the approach. Maybe allowing users to define their own typecasting functions is a bit overkill for now, but having a sort of own "hardcoded" typecasting functions would be amazing. And from there on the development needed for users to pass the functions is not that big of a deal actually, now that I think about it.

What I think will be a bit of a nightmare will be writing all the tests for that functionality (custom typecasts) xD

**Comment by philippe2803** [comment]
Datetime supports currently being added on https://github.com/socialpoint-labs/sheetfu/pull/58

**Comment by philippe2803** [comment]
Closing as Datetime now officially supported.
