### ISSUE TITLE
get_max_rows() and get_max_columns() return last row/column in sheet instead of last non-empty row

### ISSUE THREAD

**Issue by dev-awagoner** [socialpoint-labs/sheetfu#29]
I may be misunderstanding the expected output of **get_max_rows()** and **get_max_columns()**.  I expected them to return the last row/column with data.  The methods are not defined, so it's probably my misunderstanding of what they're intended to do, but I don't understand why it would be useful to report empty rows/columns.  Apologies if I've misunderstood the intent.

If the intent was to return **non-empty rows/columns**, there is an issue.  I have a simple spreadsheet, and get_max_rows() returns "990" and get_max_columns returns "26).

My sheet is 3 columns by 10 rows filled with some text and text formulas.  My expectation would be the get_max_rows() would return "10", and get_max_columns() would return "3". 

```
from sheetfu import SpreadsheetApp

spreadsheet = SpreadsheetApp("....access_file.json").open_by_id('long_string_id')
sheet = spreadsheet.get_sheet_by_name('test')
max_rows = sheet.get_max_rows()
max_cols = sheet.get_max_columns()
print(max_rows)
print(max_cols)
```

Output as mentioned above is:
```
990
26
````

**Comment by philippe2803** [comment]
@dev-awagoner just realized those methods are indeed not documented. I will add those to documentation shortly.
Unfortunately, those methods are reporting the data about the sheet, not the data, as simple as those methods are at the sheet level.

However, you can get this information quite easily with the following code:

```python

from sheetfu import SpreadsheetApp

spreadsheet = SpreadsheetApp("....access_file.json").open_by_id('long_string_id')
sheet = spreadsheet.get_sheet_by_name('test')
data_range = sheet.get_data_range()

range_max_row = data_range.coordinates.row + data_range.coordinates.number_of_rows - 1
range_max_column = data_range.coordinates.column + data_range.coordinates.number_of_columns - 1

```

`range_max_row` and `range_max_column` in that case would return the max row and the max column of the range containing data.

The code does not look amazing though, I think I will add those methods at Range level, so those are easily to get for you. the result would be as follow:

```python
data_range = sheet.get_data_range()
range_max_row = data_range.get_max_row()
range_max_column = data_range.get_max_column()
```

The only difference with your original code is the extra line getting the data range object.

**Comment by philippe2803** [comment]
@dev-awagoner should be merged early next week.

**Comment by dev-awagoner** [comment]
Thanks for the update!  I wasn't aware of the functionality for:
```
data_range.**coordinates.row**
data_range.**coordinates.column**
data_range.**coordinates.number_of_rows**
data_range.**coordinates.number_of_columns**
```
That makes things MUCH simpler!
