### ISSUE TITLE
Lost sheet reference when is using get_range().

### ISSUE THREAD

**Issue by chrosta** [socialpoint-labs/sheetfu#38]
Perhaps [this line 204](https://github.com/socialpoint-labs/sheetfu/blob/d6d2a7158e4e246f83b0206539d26eb8996afb49/sheetfu/model.py#L204) should be fixed?
`a1 = convert_coordinates_to_a1 (row, column, number_of_row, number_of_column)`
`a1 = convert_coordinates_to_a1 (row, column, number_of_row, number_of_column, self.name)`

**Comment by philippe2803** [comment]
Will look into it shortly

**Comment by stefanstmarie** [comment]
We used the proposed fix from @chrosta and that solved this issue locally.

**Comment by philippe2803** [comment]
@chrosta Thanks for reporting and proposing fix.
@stefanstmarie thanks for confirming fix works.

Will try to implement this in a coming PR. Ultimately, since it is a significantly small fix, I'm more than happy to accept PR.

**Comment by philippe2803** [comment]
This has been added in the last release (version 1.6.0)
