### ISSUE TITLE
set_field_note writing cell value, not note

### ISSUE THREAD

**Issue by mcintyre321** [socialpoint-labs/sheetfu#43]
Hi, thanks for the library - the API is exactly what I was looking for.

I'm having a problem where my call to `set_field_note` is actually updating the cell's value (which I am setting a line or two before).

        table = Table(data_range, notes=True)
        for item in table:
            row_name = item.get_field_value('Name')
            row_score_lookup = scores_lookup.get(sheet_name + '|' + row_name, {})
            for score_name, score_entry in row_score_lookup.items():
                item.set_field_value(score_name, score_entry['score'])
                item.set_field_background(score_name, score_to_colour_lookup[score_entry['score']])
                item.set_field_note(score_name, score_entry['note']) # this is setting the cell value
        
        table.commit()

It's a bit odd, but I can't figure out what's going wrong!
I'm using version 1.5.2 
Thanks in advance!

**Comment by philippe2803** [comment]
@mcintyre321 just checked the code, and you're right. There is a mistake there. Let me fix fix real quick.

**Comment by mcintyre321** [comment]
Uh oh a build error: https://travis-ci.org/github/socialpoint-labs/sheetfu/jobs/697283371

```
../../../virtualenv/python2.7.14/lib/python2.7/site-packages/googleapiclient/http.py:1763: in request
    content = six.ensure_binary(content)
E   AttributeError: 'module' object has no attribute 'ensure_binar
```

Caused by the `six` library, which broke my aws cli the other day...

**Comment by philippe2803** [comment]
That was a weird error.
In any case, it is shipped now. Make sure you take the version 1.5.3!

**Comment by mcintyre321** [comment]
Thanks for fixing this, awesome response time!
