### ISSUE TITLE
Nothing seems to work when more than 26 columns

### ISSUE THREAD

**Issue by philippe2803** [socialpoint-labs/sheetfu#47]
A few methods simply stop working when passed a certain number of columns (26).
get_range method just does not work making it difficult to work with data larger than the 26 columns.

Is this something we have encountered before?

**Comment by philippe2803** [comment]
Nevermind. It was just me who did not know how to use the library again.
I was using get_range with row and column parameter as 0 instead of 1. Could be worth handling this exception as row and column should never be 0 in the case.

**Comment by SP-alex-muelas** [comment]
Was gonna say that it could perfectly be possible because I don't think we're using sheetfu for tables that large xD Guess this can be closed
