### ISSUE TITLE
Is there a way to add rows?

### ISSUE THREAD

**Issue by evandrix** [socialpoint-labs/sheetfu#53]
on a sample Google Sheet as such:
![image](https://user-images.githubusercontent.com/169669/103378409-362d3800-4b1d-11eb-800e-aec59e233e21.png)

trying to `add_one()` row produces the following error message:
`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/<redacted spreadsheet ID>:batchUpdate?alt=json returned "Invalid requests[0].updateCells: Range (Sheet1!A3:C3) exceeds grid limits. Max rows: 2, max columns: 3">`

is there another method to add blank rows to a sheet?

**Comment by philippe2803** [comment]
The Table object expect the range queried to be already existing in the sheet. 
If the sheet only has 2 rows and you want to add a new row in your table with sheetfu and that new row falls into a range not created yet, you will get an error. It-s best to have a good number of empty rows to handle potential extra lines.
