### ISSUE TITLE
Allow setting formula

### ISSUE THREAD

**Issue by impredicative** [socialpoint-labs/sheetfu#56]
Please add functionality to allow setting a formula, especially for a Table object, but also on a range. Currently there is no way to do this.

**Comment by philippe2803** [comment]
Coming soon. currently working on it here: https://github.com/socialpoint-labs/sheetfu/pull/58

**Comment by philippe2803** [comment]
@impredicative This can now be done in the set_values method, simply by setting a value starting with "=". A string started with "=" is now automatically considered a formula.
